// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4kN1U2FAUcuy0Kpqee2QTlJ8jfri_p0M',
    appId: '1:201191598889:web:0d68ff291ac3a278c7a538',
    messagingSenderId: '201191598889',
    projectId: 'wazaa-a5b23',
    authDomain: 'wazaa-a5b23.firebaseapp.com',
    storageBucket: 'wazaa-a5b23.firebasestorage.app',
    measurementId: 'G-LH00DJGW2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuAtWnokjQad7HQ6ngNL87cVPHadEUhLY',
    appId: '1:201191598889:android:6e7e0f59099b92dbc7a538',
    messagingSenderId: '201191598889',
    projectId: 'wazaa-a5b23',
    storageBucket: 'wazaa-a5b23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRamOyF5h6zbp_3fFVE6yrouHb2G12zDA',
    appId: '1:201191598889:ios:526b41921786e613c7a538',
    messagingSenderId: '201191598889',
    projectId: 'wazaa-a5b23',
    storageBucket: 'wazaa-a5b23.firebasestorage.app',
    androidClientId: '201191598889-ivj9efvr62gtlminpkm1r28kdjkautm1.apps.googleusercontent.com',
    iosClientId: '201191598889-8bieqleq4c8222jifk19m7m2cg2mh27l.apps.googleusercontent.com',
    iosBundleId: 'com.example.misalon',
  );
}
